name: ML Pipeline

on: [push]

jobs:
 build:

  runs-on: ubuntu-latest

  steps:

  - name: Checkout Repo
    uses: actions/checkout@v3

  - name: Install Python
    uses: actions/setup-python@v4
    with:
      python-version: 3.9

  - name: Install dependencies
    run: |
      pip install "dvc[s3]==3.51.0" pandas==2.2.2 scikit-learn==1.5.1

  - name: Configure AWS
    run: |
      aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  - name: Pull dataset
    run: dvc pull

  - name: Train model
    run: python src/train.py